require('dotenv').config();
const express= require('express');
const itemRoutes = require('./routes/items');
const restaurantRoutes = require('./routes/restaurants');
const orderRoutes = require('./routes/orders');
const userRoutes = require('./routes/user');
const errorHandler = require('./middlewares/errorHandler');
const cors = require('cors');
const path = require('path');
const app = express();
const port = process.env.PORT || 5000;
const connectDB = require('./config/db');
connectDB();
app.use(express.json());
app.use(express.urlencoded({extended:false}));
app.use(cors());
app.use('/api/items', itemRoutes);
app.use('/api/restaurants', restaurantRoutes);
app.use('/api/orders', orderRoutes);
app.use('/api/users', userRoutes);
app.use(errorHandler);
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
app.listen(port, () => console.log(`server is running on port ${port}...`));